name: dart_application
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  darto: ^0.0.22
  zard: ^0.0.16

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
